pub mod linear;
pub mod slerp;
pub mod slerp_utils;
pub mod nuslerp;
pub mod multislerp;
pub mod karcher;
pub mod task_arithmetic;
pub mod ties;
pub mod dare;
pub mod della;
pub mod passthrough;
pub mod frankenmerge;
pub mod frankenmoe;
pub mod fusion;
pub mod mergekit;
pub mod arch_mapper;
pub mod orchestrator;
pub mod batch;
pub mod distributed;
pub mod latent_merge;
pub mod expert_weaver;
pub mod hetero;
pub mod moe_dense_distill;
pub mod moe_bridge;
pub mod chimera;
pub mod pocket;
pub mod aether;
pub mod breadcrumbs;
pub mod sce;
pub mod model_stock;
pub mod nearswap;
pub mod ram;
pub mod arcee_fusion;

pub use linear::LinearMerge;
pub use slerp::SlerpMerge;
pub use nuslerp::NuSlerpMerge;
pub use multislerp::MultiSlerpMerge;
pub use karcher::KarcherMerge;
pub use task_arithmetic::TaskArithmeticMerge;
pub use ties::TiesMerge;
pub use dare::DareMerge;
pub use della::DellaMerge;
pub use passthrough::PassthroughMerge;
pub use frankenmerge::{FrankenMerge, FrankenSlice, DimensionAdapter};
pub use frankenmoe::{FrankenMoE, FrankenMoEConfig};
pub use fusion::{FusionPipeline, FusionStep};
pub use mergekit::{MergeKitConfig, MergeKitLoader, to_mergekit_yaml};
pub use breadcrumbs::BreadcrumbsMerge;
pub use sce::SceMerge;
pub use model_stock::ModelStockMerge;
pub use nearswap::NearSwapMerge;
pub use ram::RamMerge;
pub use arcee_fusion::ArceeFusionMerge;
pub use arch_mapper::ArchitectureMapper;
pub use orchestrator::{execute_merge, MergeOptions};
pub use batch::{BulkMerger, BatchJob};
pub use latent_merge::LatentMerge;
pub use expert_weaver::ExpertWeaver;
pub use hetero::{HeteroMerge, HeteroMode, SlotPlan};
pub use moe_dense_distill::MoeDenseDistill;
pub use moe_bridge::MoeBridge;
pub use chimera::{ChimeraMerge, ChimeraRouter, MergeDecision, score_compat, decide};
pub use pocket::{PocketPrune, expert_score, score_experts, greedy_diverse_select, mixed_precision_plan};
pub use aether::AetherRemap;
